%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 0         
num_of_cam: 2  

imu_topic: "/mynteye/imu/data_raw"
image0_topic: "/mynteye/left/image_raw"
image1_topic: "/mynteye/right/image_raw"
output_path: "/home/zhangs/vins_fusion/"

#cam0_calib: "left_pinhole.yaml"
#cam1_calib: "right_pinhole.yaml"
cam0_calib: "left_equ.yaml"
cam1_calib: "right_equ.yaml"
#cam0_calib: "left_mei.yaml"
#cam1_calib: "right_mei.yaml"
image_width: 640 
image_height: 400

use_mynteye_adapter: 1

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-0.99984969, 0.01583498, -0.0070602, 0.04182462,
          -0.01586578, -0.99986476, 0.00432818, -0.00187427,
          -0.00699071, 0.00443954, 0.99996571, 0.00463773,
          0., 0., 0., 1. ]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-0.99985705,  0.0163996 , -0.00411503, -0.0381497,
          -0.01639405, -0.99986466, -0.00137949, -0.00328505,
          -0.0041371 , -0.00131183,  0.99999058,  0.00456543,
          0., 0., 0., 1. ]

#body_T_cam0: !!opencv-matrix
#   rows: 4
#   cols: 4
#   dt: d
#   data: [ -9.9997682265467325e-01, 6.5076367365944354e-03,
#       2.0012040300038079e-03, 3.0710470880745057e-02,
#       -6.5115707349528967e-03, -9.9997686761696203e-01,
#       -1.9656239551802640e-03, -1.1619184937249040e-02,
#       1.9883661707245873e-03, -1.9786093788315136e-03,
#       9.9999606574470934e-01, 1.3708056410108752e-02, 0., 0., 0., 1. ]
#body_T_cam1: !!opencv-matrix
#   rows: 4
#   cols: 4
#   dt: d
#   data: [ -9.9996481469059639e-01, 7.5082204823142557e-03,
#       3.7411236265824004e-03, -4.8372430610697889e-02,
#       -7.5294931542847846e-03, -9.9995537938366685e-01,
#       -5.7049079314248205e-03, -1.2162086098338444e-02,
#       3.6981229887599635e-03, -5.7328759672098219e-03,
#       9.9997672873897647e-01, 1.0449454342939922e-02, 0., 0., 0., 1. ]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)
